import './globals.css'
import { Montserrat } from "@next/font/google"

export const metadata = {
  title: 'This is the homepage',
  description: 'Generated by create next app',
}
// const montserrat = Montserrat({
//   weight: ["400", "700"],
//   subsets: ["latin"],
//   variable: "--font-montserrat",
// })

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head />
      {/* <body className={`${montserrat.className}`}> */}
      <body className="mx-32 my-12">
        {/* <nav>
          <h1>Hey I'm a header!</h1>
        </nav> */}
        {children}
      </body>
    </html>
  );
}
